### ISSUE TITLE
http in 1.19.1 causes server crash

### ISSUE THREAD

**Issue by GunnyWaffle** [replaceitem/scarpet-additions#11]
I was testing the http function in-game using the following:
```
/script run http('GET', 'https://api.mojang.com/users/profiles/minecraft/gunnywaffle', 1000, 1000)
```
It did nothing, didn't even print an error nor a return.
Then I ran it in the server console directly and it crashed the server instantly.
```
script run http('GET', 'https://api.mojang.com/users/profiles/minecraft/gunnywaffle', 1000, 1000)
[06:22:28] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: ScarpetAdditions/HttpUtils
        at ScarpetAdditions.ScarpetFunctions.http(ScarpetFunctions.java:89) ~[scarpet-additions-1.19.1-1.0.1.jar:?]
        at carpet.script.annotation.AnnotationParser$ParsedFunction.apply(AnnotationParser.java:245) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.annotation.AnnotationParser$ParsedFunction.apply(AnnotationParser.java:150) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.Expression$14.lazyEval(Expression.java:509) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.Expression.lambda$extractOp$20(Expression.java:1352) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.Expression.evalValue(Expression.java:946) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.Expression.eval(Expression.java:939) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.CarpetExpression.lambda$scriptRunCommand$13(CarpetExpression.java:111) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.utils.GlocalFlag.whileValueReturn(GlocalFlag.java:42) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.utils.GlocalFlag.getWhileDisabled(GlocalFlag.java:28) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.script.CarpetExpression.scriptRunCommand(CarpetExpression.java:111) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.commands.ScriptCommand.lambda$compute$69(ScriptCommand.java:508) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.commands.ScriptCommand.handleCall(ScriptCommand.java:440) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.commands.ScriptCommand.compute(ScriptCommand.java:506) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at carpet.commands.ScriptCommand.lambda$register$17(ScriptCommand.java:145) ~[fabric-carpet-1.19.1-1.4.83+v220727.jar:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:271) ~[server-intermediary.jar:?]
        at net.minecraft.class_2170.method_44252(class_2170.java:264) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:305) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:290) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:819) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zbe000$modifiedRunLoop(MinecraftServer.java:2885) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: ScarpetAdditions.HttpUtils
        ... 25 more
```

**Comment by replaceitem** [comment]
For some reason, the uploaded jar did not contain that class. I uploaded 1.0.2, where it is there again. No clue what happened there
